In [1]:
!pip install tabulate sklearn 

# Naive Bayes Classifier

This notebook will introduce you to the basics of the Naive Bayes Algorithm for classification tasks. It includes the following content:

- A brief overview of the Naive Bayes (NB) Classifier
- An example exercise of performing inference with NB


## What is a classifier?

A classifier is a machine learning model that is used to discriminate different objects based on specific features. Given sample data $X$, a classifier predicts the class $y$ it belongs to.

## What is a Naive Bayes Classifier?

A Naive Bayes classifier is a probabilistic machine learning model for solving classification tasks. It is based on Bayes theorem and imposes a strong assumption on feature independence.

## Bayes Theorem

$$ P(A \mid B) = \frac{P(B \mid A) \, P(A)}{P(B)} $$

We can compute the probability of event A happening, given the fact that event B has occurred. Event B is the evidence and event A is the hypothesis. The assumption made by Naive Bayes is that the features are independent, i.e. the presence of one feature does not affect the other. Therefore it is called naive.

Under the context of classification tasks, given the observation $X$, the classifier casts prediction on the class $y$. It can also be rewritten (with $y$ and $X$ replacing $A$ and $B$) as

$$ P(y \mid X) = \frac{P(X \mid y) \, P(y)}{P(X)} $$

The formula consists of four components:

- $
P(y \mid X) :
\:$ The posterior probability, which is the probability of class $y$ given the observation $X$

- $
P(y) :
\:$ The Prior probability, which is the prior probability (initial belief) of class $y$

- $
P(X \mid y) :
\:$The Likelihood, which is the probability of observation $X$ given class $y$.

- $
P(X) :
\:$The Evidence, which is the probability of observation $X$.

In classification tasks, the variable $y$ is the class label. The variable X represents the parameters/features and it usually contains multiple features/dimensions:

$$ X = (x_1, x_2, x_3, ..., x_n) $$

where $x_1, x_2, ..., x_n$ are the features and they are assumed to be independent in NB, i.e. $ (\:x_i \: \bot \:  x_j \mid y)\:\: \text{for all features}$ ($i \neq j$ and $i, j \in \{1, 2, ...., n\}$). By expanding using the chain rule we obtained the following:

$$ P(y \mid x_1, x_2, ..., x_n) = \frac{P(x_1, x_2, ..., x_n \mid y) \, P(y)}{P(X)} = \frac{P(x_1 \mid y) P(x_2 \mid y) P(x_3 \mid y) \cdots P(x_n \mid y) \, P(y)}{P(x_1) P(x_2) P(x_3) \cdots P(x_n)} $$

The denominator ($P(X)$) of the Bayes rule remains the same for all classes. Therefore, we can exclude it when performing inference since it is just a term for normalization. Therefore, based on the assumption of feature independence and ignoring the denominator the NB formula can be written as follows:

$$ P(\: y \mid x_1,x_2,...,x_n)\: \propto P(y) \prod_{i=1}^{i=n} P(\:x_i\mid y) $$

In (binary) classification tasks, the class variable $y$ has two outcomes. We need to find the class $y$ with maximum probability, i.e. $ y = argmax_y P(y) \prod_{i=1}^{i=n} P(\:x_i\mid y) $.

## An example exercise of performing inference with NB

We will use the following example to strengthen our understanding of NB. The example toy dataset is for classifying whether a person owns a pet. Observations $X$ contain three features, two categorical ("Gender" and "Education") and one numerical ("Income"), and class label $y$ (i.e. "Has_pet") corresponds to whether this person owns a pet.

In [2]:
from IPython.display import HTML, display
import tabulate
tab_cat = [["Gender", "Education", "Income", "Has_pet"],
          ["Female", "University", 103000,   "Yes"],
          ["Female", "HighSchool", 90500,   "No"],
          ["Female", "HighSchool", 114000,   "No"],
          ["Male",   "University", 102000,   "No"],
          ["Male",   "University", 75000,   "Yes"],
          ["Male",   "HighSchool", 90000,   "No"],
          ["Male",   "HighSchool", 85000,   "Yes"],
          ["Male",   "University", 86000,   "No"]]
display(HTML(tabulate.tabulate(tab_cat, tablefmt='html')))


def separating_data(data):
    sep = dict()
    for i in range(len(data)):
        vector = data[i]
        class_value = vector[-1]
        if (class_value not in sep):
            sep[class_value] = list()
        sep[class_value].append(vector)
    return sep

sep = separating_data(tab_cat)
for label in sep:
    print(label)
    for row in sep[label]:
        print(row)
        

Has_pet
['Gender', 'Education', 'Income', 'Has_pet']
Yes
['Female', 'University', 103000, 'Yes']
['Male', 'University', 75000, 'Yes']
['Male', 'HighSchool', 85000, 'Yes']
No
['Female', 'HighSchool', 90500, 'No']
['Female', 'HighSchool', 114000, 'No']
['Male', 'University', 102000, 'No']
['Male', 'HighSchool', 90000, 'No']
['Male', 'University', 86000, 'No']


<div class='alert alert-block alert-success' style="font-weight:bolder">

### Task 2a - Compute the Likelihood table of having pet, for each categorical feature, as well as the marginal probability.

- $P(Gender|Has\_pet)$: $P(Male|Yes)$, $P(Female|Yes)$, $P(Male|No)$, $P(Female|No)$
    
- $P(Education|Has\_pet)$: $P(University|Yes)$, $P(HighSchool|Yes)$, $P(University|No)$, $P(HighSchool|No)$
    
</div>

In [3]:
tab_likelihood_gender = [
    ["likelihood","-",  "Has_pet", "-", "-"],
    ["-",          "-",  "Yes", "No", "P(Gender)"],
    ["Gender", "Male", "2/3", "3/5", "5/8"], 
    ["-", "Female",    "1/3", "2/5", "3/8"],
    ["-", "P(Has_pet)","3/8", "5/8", ""]
]
display(HTML(tabulate.tabulate(tab_likelihood_gender, tablefmt='html')))


tab_likelihood_gender = [
    ["likelihood","-",  "Has_pet", "-", "-"],
    ["-",          "-",  "Yes", "No", "P(Education)"],
    ["Education", "University", "2/3", "2/5", "4/8"], 
    ["-", "HighSchool", "1/3", "3/5", "4/8"],
    ["-", "P(Has_pet)", "3/8", "5/8", ""]
]
display(HTML(tabulate.tabulate(tab_likelihood_gender, tablefmt='html')))

<div class='alert alert-block alert-success' style="font-weight:bolder">

### Task 2b - Compute the posterior probability

- $P(\text{No}|\text{Male})$, $P(\text{Yes}|\text{Female})$
    
- $P(\text{Yes}|\text{Univeristy})$, $P(\text{No}|\text{HighSchool})$

</div>


In [ ]:
P(No|Male) : P(Male|No)P(No)/P(Male)
             = (3/5)(5/8)/5/8
             = 0.6

            
P(Yes/Female):P(Female|yes)P(Yes)/P(Female)
             =(1/3)(3/8)/3/8
             = 0.333 
        
P(Yes|University) : P(University|Yes)P(Yes)/P(University)
                    =(2/3)(3/8)/4/8
                    =0.5
               
        
P(No|HighSchool) : P(HighSchool|No)P(No)/P(HighSchool)
                    =(3/5)(5/8)/4/8
                    =0.75

<div class='alert alert-block alert-success' style="font-weight:bolder">

### Task 2c - Compute the Likelihood of having pets using mean, standard deviation, and normal distribution function:

- Mean: $ \mu = \frac{1}{n} \sum^{n}_{i=1}{x_i} $
    
- Standard Deviation $ \sigma = \left[ \frac{1}{n-1} \sum^{n}_{i=1}{(x_i-\mu)^2} \right]^\frac{1}{2}  $
    
- Normal Distribution $f(x)=\dfrac{1}{\sigma\sqrt{2\pi}}\,e^{-\dfrac{(x-\mu)^2}{2\sigma{}^2}}$
    
Compute $L( \text{Income}=90000 \mid \text{Yes})$, $L( \text{Income}=90000 \mid \text{No})$

</div>

In [25]:
from math import sqrt
from IPython.display import HTML, display
import tabulate
import numpy as np
from scipy.stats import norm
import math 

# Calculate the standard deviation of a list of numbers
def stdev(numbers):
    avg = mean(numbers)
    variance = sum([(x-avg)**2 for x in numbers]) / float(len(numbers)-1)
    return sqrt(variance)

def normal_dist(x , mean , sd):
    prob_density = 1/(sd* math.sqrt(2*np.pi)) * np.exp(-((x-mean)**2)/(2*sd**2))
    return prob_density

tab_cat_yes = [["Gender", "Education", "Income", "Has_pet"],
              ["Female", "University", 103000,   "Yes"],
              ["Male",   "University", 75000,   "Yes"],
              ["Male",   "HighSchool", 85000,   "Yes"]]
display(HTML(tabulate.tabulate(tab_cat_yes, tablefmt='html')))    

print("\n")

tab_cat_no = [["Gender", "Education", "Income", "Has_pet"],
              ["Female", "HighSchool", 90500,   "No"],
              ["Female", "HighSchool", 114000,   "No"],
              ["Male",   "University", 102000,   "No"],
              ["Male",   "HighSchool", 90000,   "No"],
              ["Male",   "University", 86000,   "No"]]
display(HTML(tabulate.tabulate(tab_cat_no, tablefmt='html')))

income_yes = [103000, 75000, 85000]
income_no = [90500, 114000, 102000, 90000, 86000]
meanYes = np.mean(income_yes)
meanNo = np.mean(income_no)

incomeYes_std = stdev(income_yes)
incomeNo_std = stdev(income_no)

print("The mean for Yes",meanYes)
print("The mean for No", meanNo)

print("The standard deviation for Yes", stdev(income_yes))
print("The standard deviation for No", stdev(income_no))

print(normal_dist(90000, meanYes, incomeYes_std ))
print(normal_dist(90000, meanNo, incomeNo_std))


The mean for Yes 87666.66666666667
The mean for No 96500.0
The standard deviation for Yes 14189.197769195176
The standard deviation for No 11456.4392373896
2.7738319144377918e-05
2.964556139060196e-05


<div class='alert alert-block alert-success' style="font-weight:bolder">

### Task 2d - Making inference

- $X=(Education=University, Gender=Female, Income=100000)$
    
- $X=(Education=HighSchool, Gender=Male, Income=92000)$

</div>



In [37]:
print(normal_dist(100000, meanYes, incomeYes_std ))
print(normal_dist(100000, meanNo, incomeNo_std ))

print(normal_dist(92000, meanYes, incomeYes_std ))
print(normal_dist(92000, meanNo, incomeNo_std))

print("_____________________")

P_University = 0.5
P_Female = 3/8
X1 = P_University * P_Female * 1.927051888679545e-05 * (3/8)
X2 = P_University * P_Female * 3.323482022842907e-05 * (5/8)

print(X1)
print(X2)

print("_____________________")
P_Highschool = 0.5
P_male = 5/8
X1 = P_Highschool * P_male * 2.6834872035767643e-05 * (3/8)
X2 = P_Highschool * P_male * 1.3549583592278048e-06 * (5/8)

print(X1)
print(X2)

1.927051888679545e-05
3.323482022842907e-05
2.6834872035767643e-05
3.2237228132356433e-05
_____________________
1.3549583592278048e-06
3.894705495519032e-06
_____________________
3.1447115666915206e-06
2.646403045366806e-07


<div class='alert alert-block alert-success' style="font-weight:bolder">

### Task 2e (Extra Credit) Implementing a Naive Bayes Classifier and performing classification on the Iris dataset. Note that the Iris dataset only contains numerical features.

</div>




In [3]:
from sklearn.datasets import load_iris
iris = load_iris()
X, y = iris["data"], iris["target"]
print("data", X)
print("class/label", y)

data [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3